<template>
    <div id="employee-table">
        <table>
            <thead>
                <tr>
                    <th>Employee Name</th>
                    <th>Employee Email</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        Kamala 
                    </td>
                    <td>kamala99@gmail.com</td>
                </tr>
                <tr>
                    <td> Danushka </td>
                    <td>danushka20@gmail.com</td>
                </tr>
            </tbody>
        </table>
    </div>

</template>
<script>
export default {
    name:'employee-tables'
}
</script>

<style scoped>

</style>